### ISSUE TITLE
feat: MCU cool features to add!

### ISSUE THREAD

**Issue by maxime1907** [srcdslab/sm-plugin-mapchooser-extended#1]
- [x] sm_unnominate 
- [x] sm_showmapconfig
- [ ] Allows multiple nominations for every map (mce_nominate_mode)
- [x] See who nominated the map which won the vote
- [x] sm_nomban
- [x] Add a button to `1. Hide all unavailable maps` before any maps

https://github.com/tilgep/Mapchooser-Unlimited/
Release commit will be co-authored by [MCU Contributors](https://github.com/tilgep/Mapchooser-Unlimited/graphs/contributors) as credit.

**_This issue will be updated when a feature is added progressively_**

**Comment by Rushaway** [comment]
I have added in MCE 1.11.5
- sm_showmapconfig
- See who nominated the map which won the vote `(mce_shownominator)`
- Numbers of Extend is now handled in mapchooserextended.cfg
- Mapchooser version command

I dont plan to add `Allows multiple nominations for every map (mce_nominate_mode)` since its the major feature of MCU. 

In NE 1.12.0
- sm_unnominate
- sm_nomban
- Rebuild nominations menu to include :
 `1. Hide all unavailable maps before any maps`
 `2. Your nominated maps (Unnominate)`
 `3,4,5,.. Maps...`
